#!/usr/bin/env sh

# Wiki - https://github.com/koekeishiya/yabai/wiki

# Load scripting addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Include necessary signals for yabai-indicator
source "${HOME}/.config/yabai/indicatorrc"

# BAR HEIGHT
BAR_HEIGHT=0 #$(sketchybar -m --query bar | jq -r '.height')

GENERAL=(
    external_bar all:"${BAR_HEIGHT}":0
    split_type auto
    split_ratio 0.5
    auto_balance off
    insert_feedback_color 0xff282a36
)

LAYOUT=(
    layout bsp
    top_padding 6
    bottom_padding 6
    left_padding 6
    right_padding 6
    window_gap 8
)

WINDOWS=(
    window_placement second_child
    window_shadow float
    window_opacity off
    active_window_opacity 1.0
    normal_window_opacity 0.97
    window_opacity_duration 0.15
    window_animation_duration 0.0
    window_origin_display cursor # (options: default, focused, cursor)
)

MOUSE=(
    mouse_modifier alt # (default: fn)
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap
    focus_follows_mouse off # (options: autofocus, autoraise)
    mouse_follows_focus off
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${MOUSE[@]}"

# Include space & app management rc files
source "${HOME}/.config/yabai/spacerc"
source "${HOME}/.config/yabai/apprc"
