import = ["/Users/gldtn/.config/alacritty/themes/night-shift.toml"]

[env]
  TERM = "xterm-256color"

[window]
  padding.x = 16
  padding.y = 16
  dynamic_padding = false
  decorations = "Buttonless"

[font]
  normal.family = "FiraCode Nerd Font"
  normal.style = "Light"
  bold.family = "MonoLisa"
  bold.style = "Bold"
  size = 18

[colors]
draw_bold_text_with_bright_colors = true
